### ISSUE TITLE
Connection to domain not working?

### ISSUE THREAD

**Issue by andrearama** [testdrivenio/django-on-docker-letsencrypt#5]
Hello,
thanks for the great tutorial and code. Been really helpful.
Still pretty newbie when it comes to django, and although this tutorial has helped my a lot, I am facing now some problems I couldn't solve so far. I tried both to follow the tutorials step by step and to directly clone this repo, but still I can not solve the problem.

I bought a domain, that is www.datajobs.xyz.
I tried to change the .env.staging file adding my domain :

`DEBUG=0`
`SECRET_KEY=change_me`
`DJANGO_ALLOWED_HOSTS=www.datajobs.xyz `
`SQL_ENGINE=django.db.backends.postgresql `
`SQL_DATABASE=hello_django_prod `
`SQL_USER=hello_django `
`SQL_PASSWORD=hello_django `
`SQL_HOST=db `
`SQL_PORT=5432 `
`DATABASE=postgres `
`VIRTUAL_HOST=www.datajobs.xyz `
`VIRTUAL_PORT=8000`
`LETSENCRYPT_HOST=www.datajobs.xyz `

and my email in .env.staging.proxy-companion:

`DEFAULT_EMAIL=andrea@datajobs.xyz `
`ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory `
`NGINX_PROXY_CONTAINER=nginx-proxy `

 I build and spin the containers as usual:
`docker-compose -f docker-compose.staging.yml up -d --build`
`docker-compose -f docker-compose.staging.yml exec web python manage.py migrate --noinput`

I am not getting any error, but when I then visit www.datajobs.xyz , I just see the default page of the domain provider telling me that this domain has been bought by someone. 
I do not understand what is the problem. Any suggestions? 

Thanks a lot,
Andrea

P.S: I am running this from local (Ubuntu) machine, and not a virtual one. But I would guess that is not the problem

**Comment by mjhea0** [comment]
You can't do this from your local machine. You'll have to deploy it somewhere and then point your domain name to it.
